### ISSUE TITLE
artwork size resizizes smallest side

### ISSUE THREAD

**Issue by bardware** [nu774/qaac#104]
I was looking at .m4a files I created with this tool from .flac files.
I use the parameter `--artwork-size 256` and see the image in the resulting file has dimension `284x256`

I had expected the largest size was resized to 256 pixels.
[Blame](https://github.com/nu774/qaac/blame/49d25bdf0fbc7fffe8b162399c2c5cbb712a6528/wicimage.cpp#L81) says this code dates back to 12 years ago. It still came as a surprise.

Can you image to change this parameter to act on the largest side of the image?

Thank you for maintaining this software.

**Comment by nu774** [comment]
Thanks, this is indeed counterintuitive. Fixed on v2.83.
