### ISSUE TITLE
Fails to convert from FLAC to ALAC

### ISSUE THREAD

**Issue by ghost** [nu774/qaac#24]
When I run the following command:

.\qaac.exe -A '.\MyMusic.flac'

I get this error:

qaac 1.39, CoreAudioToolbox 7.9.7.9

MyMusic.flac
ERROR: Not available input file format

Any ideas?

**Comment by birdie-github** [comment]
Version 1.3.3 which works (courtesy of John33/rarewares.org)

[libFLAC.zip](https://github.com/nu774/qaac/files/6872839/libFLAC.zip)

**Comment by Nisekoi-1** [comment]
thanks

**Comment by itsTyrion** [comment]
That's the 32 bit DLL. Here's the 64-bit one:
[flac_dll-1.3.4-x64-772efde.zip](https://github.com/nu774/qaac/files/9260704/flac_dll-1.3.4-x64-772efde.zip)

taken form https://rarewares.org/lossless.php
