### ISSUE TITLE
Converting to CVBR 32kbps causes unexpected corruption

### ISSUE THREAD

**Issue by insanetesterftw** [nu774/qaac#32]
1st of all, I known that converting to 32kbps will cause audio degradation, that is not of I'm reporting.

When converting a flac file to 32kbps CVBR HE the resulting file ends with pop and skips that are absent from the original. I used Foobar2000 as a frontend with the following settings: qaac 2.47, CoreAudioToolbox 7.9.9.6, AAC-HE Encoder, CVBR 32kbps, Quality 96. I used another frontend with the same settings and the same thing happened.

It should be noted that I converted a batch of files with the same settings and that one is the only one until now that presented problems.

I then decided to convert to 40kbps and the resulting file is clean without the skips and pops.

I also tested the FhG converter at 32kbps and the those files are clean.

So, the corruption only occurs with that specific file, with qaac, with that specific settings.

**Comment by insanetesterftw** [comment]
I noticed that I was using an older version and I've retested with the most recent version: qaac 2.52, CoreAudioToolbox 7.9.9.6, AAC-HE Encoder, CVBR 32kbps, Quality 96.

The same result. Still corrupted.

**Comment by nu774** [comment]
Try the same with iTunes and see what you get.
If you are having the same result, it's not qaac's fault.

**Comment by insanetesterftw** [comment]
After fighting with iTunes very poor interface I finally could reproduce all the settings that I used. 

It also occurs with iTunes. It only occurs in the following combination of settings: 32kbps and 44.100kHz. With 32kbps and 32.000kHz doesn't. With 40kbps and 44.100kHz also doesn't.

The strange thing is that only occurs with this song. I've three versions (from different albums) of this song and all end up with same corruption. None of the other songs were corrupted with same settings.

I'm thankful for your help.

I'm stuck! What now?

**Comment by nu774** [comment]
So, it's the issue in the Apple's encoder.
Maybe you can try different setting or another encoder for that sample.

**Comment by insanetesterftw** [comment]
Sorry if I keep this issue open since it's no longer your responsability. But i need to correct my previous comment.

Audio corruption still occurs at 40kbps only in a different set of files. Apple's aac encoder cannot be trusted.

And, yes, I change my choice of encoder from Apple's to FhG's.
