### ISSUE TITLE
Mono Encode Broken

### ISSUE THREAD

**Issue by czchmate** [nu774/qaac#34]
Encoding of mono source files is broken in version 2.55. It still works in version 2.54 when using all of the same DLLs (wavpack, FLAC, libsndfile, and the latest AppleApplicationSupport). I took a long look at the code but my incredibly basic coding ability did not let me see where the error was.

**Comment by nu774** [comment]
Works here.
Can you provide a sample file and let me know *how* it is broken?

**Comment by czchmate** [comment]
When I built 2.55 on my Windows 10 machine, I was getting the Not Supported Channel Layout message that is contained in chanmap.cpp. Version 2.54, built on the same machine, was properly processing mono .wav and .flac source files to mono-configured .m4a files (ALAC and AAC). I just built it on a Windows 7 machine using Microsoft Visual Studio Express 2013 for Windows Desktop, Version 12.0.21005.1 REL and Microsoft .NET Framework, Version 4.5.50938 and now, bizarrely, it seems to be working, but instead, it is converting the source (.wav or .flac) to stereo .m4a when it used to retain the mono configuration.

The source audio files originally came from a dub of vinyl that I made using Audacity 2.1.2 at 32-bit float, 96,000 Hz, edited, and then exported at 32-bit float, 96,000 Hz .wav (I tried using the ffmpeg plugin and through the native export function, trying 16-bit 44,100 Hz export, as well (signed, unsigned, little-endian, and big-endian). Then I resampled and dithered the source with ffmpeg to 16-bit signed little-endian 44,100 Hz .wav using command line "ffmpeg -i [filename] -acodec pcm_s16le -ar 44100 -dither_method triangular [filename].wav" (error persisted with or without the dither effect specification on all methods of export tried in Audacity). With QAAC, I tried multiple command functions in both the 32-bit and 64-bit compilations, my main command is usually "qaac64 -V 100 --gapless-mode 2 --threading [filename]".

I should add that when I tried the command, "qaac64 -R --raw-format S16L --raw-rate 22500" it output a .M4A file at proper speed (--raw-rate 44100 produced a double speed file). Unfortunately, I don't have access to the Windows 10 machine at the moment or the QAAC 2.55 compiled on it at this moment.

qaac64 --check (Windows 7 Compiled (Stereo Output))
qaac 2.55, CoreAudioToolbox 7.10.5.0
libsndfile-1.0.25
libFLAC 1.3.1
wavpackdll 4.75.0

Everything was performed on 64-bit machines.

**Comment by czchmate** [comment]
Oh, yeah, ffmpeg on the Windows 7 machine (which processes QAAC 2.55 mono input to stereo .m4a output) is N-76704-ge9aea6d compiled with gcc 5.2.0. Same 32-bit float, 96,000 Hz source for both.

**Comment by czchmate** [comment]
Sorry. One more update. I can also confirm that the QAAC 2.54 compiled with and using the Windows 7 machine processes mono sources to stereo .m4a. For certain, the 2.54 processes to mono .m4a on the Windows 10 machine. Could be the iTunes installation on the particular machines? Would QAAC prefer system AppleApplicationSupport .DLLs over the versions in the local folder?

**Comment by czchmate** [comment]
Alright. I tried recompiling 2.55 on my Windows 10 machine and everything seems okay. As to the stereo versus mono issue, I think it was just a problem in what VLC was displaying. Foobar shows the correct, single channel configuration. Maybe it was the development version that I was having trouble with? Not sure. Anyway, forget the whole issue. I'm sorry that I wasted your time.
