### ISSUE TITLE
mulichannel alac encoding, help needed

### ISSUE THREAD

**Issue by Selur** [nu774/qaac#35]
> ffmpeg -y -threads 8 -i "H:\Temp\iId_3_aid_1_DELAY_-44ms_10_47_50_3710_01.ac3" -ac 6 -ar 48000 -c:a alac  -f ipod h:\Temp\ffmpeg_alac.m4a

creates multichannel alac

using qaac 2.5.5
> ffmpeg -y -threads 8 -loglevel fatal -i "H:\Temp\iId_3_aid_1_DELAY_-44ms_10_47_50_3710_01.ac3" -ac 6 -ar 48000 -acodec pcm_s16le -f wav - | qaac --delay -0.044 --threading --alac --raw - -o "H:\Temp\iId_3_aid_1_aa.m4a"

only creates stereo output

Do I have to specify anything special to create multichannel alac with qaac ?

**Comment by nu774** [comment]
Remove --raw option.
