### ISSUE TITLE
Decoding From Mono Input Won't Allow Re-Encoding

### ISSUE THREAD

**Issue by czchmate** [nu774/qaac#37]
Alright, I finally figured out what I did that broke the mono encode that I reported and then retracted previously. I take an AAC file that was encoded in mono using qaac 2.54 and then decode it to WAV. When using that file to try to recompress to ALAC or AAC, I get "Error: No Channel mapping to AAC defined". I get the same error when specifying --chanmap 1. When I use --chanmask 0 I get "ERROR: Not supported channel layout".

If I take the same WAV and try to encode it using qaac 2.54 it works perfectly normal.

All stereo WAV sources work properly, including taking the same Mono WAV, doubling up the track and converting it to a stereo WAV in Audacity.

I've also tried using a stereo AAC that was encoded with qaac 2.48, converting it to mono with Audacity and then encoding. I get the same errors.

The qaac 2.57 executables were created using Microsoft Visual Studio Express 2013 on a Windows 7 machine and also using the default project settings.

My Versions Are As Follows:
qaac 2.57
CoreAudioToolbox 7.10.5.0
libsndfile-1.0.26
libFLAC 1.3.1
wavpackdll 4.75.0

**Comment by nu774** [comment]
Thanks, fixed on 2.58.
