### ISSUE TITLE
qaac vs Wavpack v5 alpha releases (under Linux and Wine)

### ISSUE THREAD

**Issue by andrew-strong** [nu774/qaac#39]
I have cross compiled Alpha 1 and Alpha 2 of Wavpack 5.0.0 and successfully used the generated libwavpack-1.dll with qaac 2.59. However qaac will not use the Alpha 3  Wavpack 5.0.0 libwavpack-1.dll for input when cross compiled in the same manner.

I confess I am unsure if it is my compiling technique or an adjustment that needs to be made in qaac. But to eliminate possible user error I have just now retested each build and I can confirm that on my setup:
1. Alpha 1 & 2 builds of wavpack dll work with qaac
2. Alpha 3 builds of wavpack dll  do not work with qaac

Thanks for looking at this, and a big thanks for qaac :)

Andrew

**Comment by nu774** [comment]
Tried with the latest commit (c068e59) of wavpack, and seems working here with qaac 2.59.
qaac 2.59 still uses alpha1 wavpack header which lacks some of recently added functions, but should be binary compatible with alpha3.

Try with my build at https://dl.dropboxusercontent.com/u/76042064/wavpack5.0.0-alpha3.7z
(I also cross compiled on the Linux)

**Comment by andrew-strong** [comment]
Thank you very much for going to all that trouble. I have tested your build of the wavpack dll  on my system with the same result: import of wavpack files does not work and `qaac --check` does not show wavpack.

Seems odd... I have not mentioned my running environment which is running [qaac via wine on Slackware Linux](http://www.andrews-corner.org/qaac.html), this has not given me issues before; I am using the 32 bit dll.

If nothing shows at your end I will return to either Alpha 1 or the older release version and await the full release of wavpack 5.0.0.

Thank you again for looking at this issue,

Andrew

**Comment by andrew-strong** [comment]
Just cross compiled wavpack alpha 4 and certainly on my system `qaac --check `still does not recognise the wavpack library. Puzzling that it works at your end but not mine....

**Comment by nu774** [comment]
Well, if you build wavpack with --disable-static and create wavpack.exe and libwavpack-1.dll, does wavpack.exe work with libwavpack-1.dll just fine?

**Comment by andrew-strong** [comment]
Thanks again for getting back to me and my apologies for taking up your time on what is doubtless a user error at my end. After further experimentation as you have suggested I have decided to retreat to the older version of wavpack dll which imports perfectly on my system.

And thanks for qaac :)

**Comment by andrew-strong** [comment]
I have returned to this issue as it still confounds me a little, and looking back on my original question I can see that I have left out the vital issue that I am actually running qaac from Linux using Wine. My apologies for this now obvious problem:

 I have rebuilt alpha 5 version wavpack for 32bit Windows (using MXE) and tested the executable as you have suggested (under Windows):

```
C:\Users\andrew\Desktop\testing\bin>wavpack --version
wavpack 5.0.0-alpha5
libwavpack 5.0.0-alpha5

C:\Users\andrew\Desktop\testing\bin>wavpack.exe luckynight.wav

 WAVPACK  Hybrid Lossless Audio Compressor  Win32 Version 5.0.0-alpha5
 Copyright (c) 1998 - 2016 David Bryant.  All Rights Reserved.

 *** This is an experimental alpha version and should be used for ***
 *** testing only. Please do not use it for important archiving!! ***

created luckynight.wv in 0.50 secs (lossless, 37.92%)                                                                       
C:\Users\andrew\Desktop\testing\bin>
```
Working perfectly! And the wavpack dll works nicely with qaac under a native Windows environment:
```
C:\Users\andrew\Desktop\qaac>qaac --check
qaac 2.61, CoreAudioToolbox 7.9.9.6
libsoxconvolver 0.1.0
libsoxr-0.1.3b1
libsndfile-1.0.25
libFLAC 1.3.1
wavpackdll 5.0.0-alpha5
tak_deco_lib 2.3.0 compatible

C:\Users\andrew\Desktop\qaac>
```
But does not work under Wine from a native Linux environment where the wavpack dll is ignored. This is with:

```
andrew@ilium~$ wine --version                                                                         
wine-1.9.15 (Staging)
andrew@ilium~$ 
```
I quite openly admit this might very well be a Wine issue that you may have no interest in but I would be happy to hear your thoughts on this issue now that I seem to have come to the root of it.

**Comment by andrew-strong** [comment]
I have just built the newly released Wavpack 5 and I still see the same issue under Linux and Wine: the Wavpack dll is not recognised. Under a native Windows environment all is well...

**Comment by andrew-strong** [comment]
Solved with the newest 'official' dlls from Wavpack site :)
