### ISSUE TITLE
Malware detected - Trojan: Win32/Maltule.C!cl

### ISSUE THREAD

**Issue by nekno** [nu774/qaac#41]
First let me say, I assume this is a false-positive and I just want to figure out if there's a good way (for all users) to prevent getting a malware warning. Also, if others encounter the malware warning, they can find this issue.

When extracting or copying `qaac64.exe` and `refalac64.exe` v2.61, Windows Defender is detecting a Trojan it calls `Win32/Maltule.C!cl`. Microsoft provides [basically no info on it](https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fMaltule.C!cl).

I can only find [one other reference](https://www.svp-team.com/forum/viewtopic.php?pid=59948#p59948) to another user encountering this warning with qaac, but still, it indicates it isn't just me.

[A scan of `qaac64.exe` with VirusTotal](https://www.virustotal.com/en/file/3edbc0de61b0ebad93249a0afb56cd014208d373d4c833ac1898359d1a108c5c/analysis/1477256648/) yielded no malware. I [submitted a report](https://www.microsoft.com/en-us/security/portal/submission/submit.aspx) of the false positive to Microsoft.

I was updating from qaac 2.59 and didn't encounter this issue with that version. Any ideas on changes that might have triggered the new warning?

---

![maltule c](https://cloud.githubusercontent.com/assets/4205478/19629366/7403ec72-9939-11e6-99a1-071bcb23b932.PNG)

**Comment by nu774** [comment]
Yeah, I've noticed that on 2.6.0 (about a month ago), and have already reported to MS myself.
I really have no idea about it.

**Comment by nekno** [comment]
That's too bad. No malware was detected in my submission of 2.61 to MS, so perhaps we just have to hope that it was due to out-of-date malware definitions.

```
  Submitted Files
  =============================================
  qaac_2.61.zip [Not Malware]
  +---qaac_2.61_x64_libsoxconvolver64.dll [Not Malware]
  +---qaac_2.61_x86_libsoxconvolver.dll [Not Malware]
  +---qaac_2.61_x64_libsoxr64.dll [Not Malware]
  +---qaac_2.61_x86_libsoxr.dll [Not Malware]
  +---qaac_2.61_x64_qaac64.exe [Not Malware]
  +---qaac_2.61_x64_refalac64.exe [Not Malware]
  +---qaac_2.61_x86_qaac.exe [Not Malware]
  +---qaac_2.61_x86_refalac.exe [Not Malware]

Your submission was scanned using antimalware definition version 1.231.258.0.
```
