### ISSUE TITLE
qaac 2.6.2 のwavpack-dsdについて

### ISSUE THREAD

**Issue by Heiseikiseki** [nu774/qaac#44]
早速のリリースありがとうございます。
うまく変換できました。
ただし、WAVPACK－DSDからAACに変換すると、タグが継承されてない模様です。
修正可能でしょうか。

**Comment by nu774** [comment]
タグ関連は特に仕様は変わっていないはずなので、wavpackのライブラリが読める形で(APEv2形式で)タグが入っているのであれば、qaac側からも読めるはずです（こちらでは読めます）。

**Comment by Heiseikiseki** [comment]
再確認しましたが、WV（PCM）なら読めますが。
DSF－＞WV(DSD）に変換すると
そのWVをQAACに入れると必ずタグが継承されません。
もしかすると、DSFからWVに変換する場合は元のID3v2形式のタグをWVにコピーするだけです。
今日も似たような問題をスレを見ました、宜しければご参考に
https://sourceforge.net/p/sacddecoder/feature-requests/50/

**Comment by nu774** [comment]
タグのついたDSFをwavpackのコマンドラインエンコーダーでエンコードした（だけの）ものをqaacに読み込ませるとqaac側でタグが読めないという話でしょうか？
でしたら、qaac側でそれを読めないのは仕様ですね。

wavpackコマンドは元ファイルのタグをwavpackファイルのAPEv2タグにコピーはしないので(ただし、復元のためにタグを含む元のコンテナ情報を丸ごとファイル内部に保存はする)、wavpackファイルとしてはタグ無い状態となっているのです。
foobar2000などで、wavpackファイルを(APEv2で)タグ付けすれば、qaacで読めるはずです。

**Comment by Heiseikiseki** [comment]
はい、その通りです。
わかりました、RETAGしてみます。
