### ISSUE TITLE
Delay is applied at the start despite using --no-delay

### ISSUE THREAD

**Issue by pcroland** [nu774/qaac#52]
The first sound is the source, the second one is an aac using `-V 82 --no-delay --no-smart-padding --adts`, the third one is an aac using `-V 82 --no-smart-padding --adts`
https://vgy.me/StER9g.png
So it doesn't really matter if I use --no-delay or not, the outputs even have the same md5sum.

**Comment by nu774** [comment]
You cannot enable --no-delay and --no-smart-padding at the same time.
Basically, don't use --no-smart-padding unless you have a strong reason to do so (for example, testing bit-exactness against iTunes).
