### ISSUE TITLE
Please update Examples on the Wiki: how to consume stdin and output to stdout

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nu774/qaac#60]

**Comment by vitaly-zdanevich** [comment]
Hm, with `-o -` I got `MP4 piping is not supported`. Strange, why?

**Comment by nu774** [comment]
```
qaac 2.64
Usage: qaac [options] infiles....

"-" as infile means stdin.
On ADTS/WAV output mode, "-" as outfile means stdout.
```

As is written in help message, "-" as outfile is not supported for MP4 output.
(MP4 output requires seeking, and you can't seek on pipe)

**Comment by vitaly-zdanevich** [comment]
Hm, this is sad that I will need to write aac to SSD and read it from SSD for uploading to S3 :(
