### ISSUE TITLE
qaac support for mka/mkv container

### ISSUE THREAD

**Issue by nobananasforyou** [nu774/qaac#64]
Hello,

Would it be possible to add mkv/mka support to qaac? I would really appreciate it. 

Thank you!

**Comment by nu774** [comment]
Matroska is indeed very popular format for video, but how many use mkv/mka for audio?

As far as I know, there's NO audio encoder that directly output to matroska, and no providers sell music files in matroska.
Therefore you have to manually run ffmpeg, mkvmerge or something to get mka file, but for what reason people even bother to do so?

You can always pipe from ffmpeg, foobar2000 or something. Isn't it enough?
I don't think matroska deserves native support in qaac.

**Comment by nobananasforyou** [comment]
Mainly for blu-ray remux/demuxing via mkvtoolnix. There's no need to bother with ffmpeg and foobar2000 when I can use just mkvtoolnix to achieve the same task. The only problem being matroska support.

**Comment by nu774** [comment]
> Mainly for blu-ray remux/demuxing via mkvtoolnix.

So there's no tags to import, and you want not only matroska support but also decoder for DTS-MA, TrueHD, pcm-bluray or something.

Direct support by qaac is useful when you want to automatically copy tags. However, if there's no need to copy tags, you can achieve the same thing just by piping.
What you want requires so many things to implement, and gains almost nothing.

**Comment by nobananasforyou** [comment]
okay.
