### ISSUE TITLE
QAAC does not work on versions iTunes >=12.10.9.3

### ISSUE THREAD

**Issue by aikoofujimotoo** [nu774/qaac#72]
iTunes Installers no longer bundles Apple Application Support starting 12.10.9.3
See https://www.theiphonewiki.com/wiki/ITunes#64-bit

![screenshot](https://aikoooo.web.fc2.com/u/f9ecc0cd-cefd-4520-9ff5-9518d2813c9f-1604138272-646x56.jpg)
![iTunes Version Installed](https://aikoooo.web.fc2.com/u/b5af4d10-1a7e-486d-adbc-7c64213b599c-1604138350-612x364.jpg)

Edit: Use version 2.70 or greater instead.

**Comment by ValZapod** [comment]
And so what?
