### ISSUE TITLE
Got issue when convent Flac to applelessloss

### ISSUE THREAD

**Issue by N2022062** [nu774/qaac#79]
use foobar
set Parameters to --ignorelength -s --no-optimize --alac --no-smart-padding -v256 -q2 -o %d -

got issue when covent 

so how to set the parameters?

1 out of 1 files converted with major problems.

Source: ".......flac"
  An error occurred while writing to file (The encoder has terminated prematurely with code 1 (0x00000001); please re-check parameters) : "E:\01 christopher cross - ride like the wind.m4a"
  Additional information:
  Encoder stream format: 44100Hz / 2ch / 16bps
  Command line: "D:\Music\Foobar2000\encoders\qaac64.exe" --ignorelength -s --no-optimize --alac --no-smart-padding -v256 -q2 -o "01 christopher cross - ride like the wind.m4a" -
  Working folder: E:\
  Conversion failed: The encoder has terminated prematurely with code 1 (0x00000001); please re-check parameters

**Comment by nu774** [comment]
Drop "-v256 -q2". As written in the help, these options are for AAC.
