### ISSUE TITLE
normalize + delay fails with newest flac lib

### ISSUE THREAD

**Issue by FlorianGamper** [nu774/qaac#86]
I tried to convert a 6 Channel .FLAC file with Qaac64 2.76
with libFLAC_dynamic.dll v1.42 (with version 1.3x it works) 
it only happens when you use **negative start values** **and normalize**

`qaac64.exe --start -0.003 -v 500 --ignorelength ".\a.FLAC" -N -o ".\a.mp4"`

Leads to the following Error

```
qaac 2.76, CoreAudioToolbox 7.10.9.0

a.mp4
Scanning maximum peak...
[100.0%] 38:09.858/38:09.858 (400.4x), ETA 0:00.000
109913232/109913232 samples processed in 0:05.719
Peak: 0.686453 (-3.26778dB)
AAC-LC Encoder, CVBR 512kbps, Quality 96

ERROR: AudioConverterFillComplexBuffer(m_converter, staticInputDataProc, this, &npackets, abl, aspd): what
```

**Comment by nu774** [comment]
Thanks for reporting, fixed by the commit https://github.com/nu774/qaac/commit/28c4303f243502f52cf6382aa90096826d2f9a19.
